# Generated by Django 4.2.5 on 2023-10-02 13:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='end_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_hour',
            field=models.DateField(default=datetime.datetime(2023, 10, 2, 15, 5, 5, 536186)),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_hour',
            field=models.DateField(default=datetime.datetime(2023, 10, 2, 15, 5, 5, 536186)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='classroom_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.classroom'),
        ),
    ]
