# Generated by Django 4.2.5 on 2023-10-02 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_schedule_end_time_schedule_end_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_hour',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 2, 15, 6, 54, 19851)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_hour',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 2, 15, 6, 54, 19851)),
        ),
    ]
