# Generated by Django 4.2.5 on 2023-10-02 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_schedule_created_alter_schedule_end_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_hour',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 2, 17, 39, 23, 649705)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_hour',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 2, 15, 9, 23, 649705)),
        ),
    ]
