# Generated by Django 4.2.5 on 2023-10-03 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_schedule_presentce_schedule_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='presentce',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='student',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_hour',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 3, 17, 30)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_hour',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 3, 15, 0)),
        ),
    ]
