# Generated by Django 4.2.5 on 2023-10-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_schedule_presentce_remove_schedule_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='presence_list',
            field=models.JSONField(default=1, verbose_name='Presence List'),
            preserve_default=False,
        ),
    ]
