# Generated by Django 4.2.6 on 2023-11-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_schedule_end_hour_alter_schedule_start_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
