# Generated by Django 4.2.6 on 2023-11-08 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_student_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='present',
            name='notes',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_hour',
            field=models.TimeField(default=datetime.time(12, 30)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_hour',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
