# Generated by Django 4.2.5 on 2023-10-11 13:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0013_alter_schedule_end_hour_alter_schedule_start_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='created_by',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_hour',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 11, 18, 0)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_hour',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 11, 15, 30)),
        ),
    ]
