# Generated by Django 4.2.5 on 2023-10-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_classroom_created_by_alter_schedule_end_hour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='created',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='presence_list',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_hour',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_hour',
            field=models.TimeField(),
        ),
    ]
