# Generated by Django 4.2.5 on 2023-10-15 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_schedule_end_hour_alter_schedule_start_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='presence_list',
        ),
        migrations.AddField(
            model_name='student',
            name='presence_list',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_hour',
            field=models.TimeField(default=datetime.time(12, 30)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_hour',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
    ]
