# Generated by Django 4.2.5 on 2023-10-26 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_present_student_alter_schedule_end_hour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='present',
            name='presence',
        ),
        migrations.RemoveField(
            model_name='student',
            name='presence_list',
        ),
        migrations.AddField(
            model_name='present',
            name='is_present',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_hour',
            field=models.TimeField(default=datetime.time(20, 0)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_hour',
            field=models.TimeField(default=datetime.time(17, 30)),
        ),
    ]
