# Generated by Django 4.2.5 on 2023-10-27 09:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_present_presence_remove_student_presence_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='present',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.schedule'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_hour',
            field=models.TimeField(default=datetime.time(13, 30)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_hour',
            field=models.TimeField(default=datetime.time(11, 0)),
        ),
    ]
