# Generated by Django 4.2.5 on 2023-10-28 16:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0022_alter_present_schedule_alter_schedule_end_hour_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teacher_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='present',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_hour',
            field=models.TimeField(default=datetime.time(20, 30)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_hour',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
